using eGift.Admin.Common;
using eGift.Admin.Helpers;
using eGift.Admin.Models.ListViewModels;
using eGift.Admin.Models.ResponseViewModel;
using eGift.Admin.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eGift.Admin.Controllers;

public class ProductController : Controller
{
    #region Fields

    private readonly WebClientHelper _webClient;
    private readonly ILogger<ProductController> _logger;

    #endregion

    #region Constructors

    public ProductController(
        WebClientHelper webClient,
        ILogger<ProductController> logger)
    {
        _webClient = webClient;
        _logger = logger;
    }

    #endregion

    #region Product Default CRUD

    // GET: Product
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        try
        {
            var products = new ProductListViewModel();

            products.ProductList = await _webClient
                .GetAsync<List<ProductResponseViewModel>>(
                    "/api/product")
                ?? new List<ProductResponseViewModel>();

            return View(products);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                "Exception in ProductController Index: {Message}",
                ex.Message);

            TempData["ToastrType"] =
                ToastrType.Error.ToString();

            TempData["ToastrMessage"] =
                ex.Message;

            return View();
        }
    }

    // GET: Product/Details/5
    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        try
        {
            var product = await _webClient
                .GetAsync<ProductResponseViewModel>(
                    $"/api/product/{id}");

            if (product == null)
            {
                TempData["ToastrType"] =
                    ToastrType.Error.ToString();

                TempData["ToastrMessage"] =
                    "Product not found.";

                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                "Exception in ProductController Details/{id}: {Message}",
                id,
                ex.Message);

            TempData["ToastrType"] =
                ToastrType.Error.ToString();

            TempData["ToastrMessage"] =
                ex.Message;

            return RedirectToAction(nameof(Index));
        }
    }

    // GET: Product/Create
    [HttpGet]
    public async Task<IActionResult> Create()
    {
        try
        {
            var model = new ProductViewModel();

            // Load dropdown data here
            await LoadDropdowns(model);

            return View(model);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                "Exception in ProductController Create GET: {Message}",
                ex.Message);

            TempData["ToastrType"] =
                ToastrType.Error.ToString();

            TempData["ToastrMessage"] =
                ex.Message;

            return RedirectToAction(nameof(Index));
        }
    }

    // POST: Product/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ProductViewModel model)
    {
        try
        {
            // These are optional on Create because they are generated by the API
            ModelState.Remove(nameof(model.ProductImagePath));
            ModelState.Remove(nameof(model.PicturePath1));
            ModelState.Remove(nameof(model.PicturePath2));
            ModelState.Remove(nameof(model.PicturePath3));
            ModelState.Remove(nameof(model.PicturePath4));

            if (!ModelState.IsValid)
            {
                await LoadDropdowns(model);

                return View(model);
            }

            model.CreatedBy =
                Convert.ToInt32(
                    HttpContext.Session.GetInt32("UserId"));

            model.CreatedDate = DateTime.Now;

            using var formData = new MultipartFormDataContent();

            formData.Add(
                new StringContent(model.Name),
                nameof(model.Name));

            formData.Add(
                new StringContent(model.CategoryId.ToString()),
                nameof(model.CategoryId));

            formData.Add(
                new StringContent(model.SubCategoryId.ToString()),
                nameof(model.SubCategoryId));

            formData.Add(
                new StringContent(model.QuantityPerUnit.ToString()),
                nameof(model.QuantityPerUnit));

            formData.Add(
                new StringContent(model.UnitPrice.ToString()),
                nameof(model.UnitPrice));

            if (model.SizeId.HasValue)
            {
                formData.Add(
                    new StringContent(model.SizeId.Value.ToString()),
                    nameof(model.SizeId));
            }

            if (model.Discount.HasValue)
            {
                formData.Add(
                    new StringContent(model.Discount.Value.ToString()),
                    nameof(model.Discount));
            }

            formData.Add(
                new StringContent(model.UnitInStock.ToString()),
                nameof(model.UnitInStock));

            formData.Add(
                new StringContent(model.UnitInOrder.ToString()),
                nameof(model.UnitInOrder));

            formData.Add(
                new StringContent(model.ProductAvailable.ToString()),
                nameof(model.ProductAvailable));

            if (!string.IsNullOrWhiteSpace(model.ShortDescription))
            {
                formData.Add(
                    new StringContent(model.ShortDescription),
                    nameof(model.ShortDescription));
            }

            if (!string.IsNullOrWhiteSpace(model.LongDescription))
            {
                formData.Add(
                    new StringContent(model.LongDescription),
                    nameof(model.LongDescription));
            }

            formData.Add(
                new StringContent(model.IsDeleted.ToString()),
                nameof(model.IsDeleted));

            formData.Add(
                new StringContent(model.CreatedBy.ToString()),
                nameof(model.CreatedBy));

            formData.Add(
                new StringContent(model.CreatedDate.ToDateTimeString()),
                nameof(model.CreatedDate));

            // Main Product Image
            if (model.ProductImage != null &&
                model.ProductImage.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.ProductImage.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.ProductImage.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.ProductImage),
                    model.ProductImage.FileName);
            }

            // Picture 1
            if (model.Picture1 != null &&
                model.Picture1.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.Picture1.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.Picture1.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.Picture1),
                    model.Picture1.FileName);
            }

            // Picture 2
            if (model.Picture2 != null &&
                model.Picture2.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.Picture2.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.Picture2.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.Picture2),
                    model.Picture2.FileName);
            }

            // Picture 3
            if (model.Picture3 != null &&
                model.Picture3.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.Picture3.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.Picture3.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.Picture3),
                    model.Picture3.FileName);
            }

            // Picture 4
            if (model.Picture4 != null &&
                model.Picture4.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.Picture4.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.Picture4.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.Picture4),
                    model.Picture4.FileName);
            }

            await _webClient.PostFormAsync<object>(
                "/api/product",
                formData);

            TempData["ToastrType"] =
                ToastrType.Success.ToString();

            TempData["ToastrMessage"] =
                "Product created successfully.";

            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            _logger.LogError(
                "Exception in ProductController Create POST: {Message}",
                ex.Message);

            TempData["ToastrType"] =
                ToastrType.Error.ToString();

            TempData["ToastrMessage"] =
                ex.Message;

            await LoadDropdowns(model);

            return View(model);
        }
    }

    // GET: Product/Edit/5
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        try
        {
            var model = await _webClient
                .GetAsync<ProductViewModel>(
                    $"/api/product/{id}");

            if (model == null)
            {
                TempData["ToastrType"] =
                    ToastrType.Error.ToString();

                TempData["ToastrMessage"] =
                    "Product not found.";

                return RedirectToAction(nameof(Index));
            }

            // Load dropdown data here
            await LoadDropdowns(model);

            return View(model);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                "Exception in ProductController Edit GET: {Message}",
                ex.Message);

            TempData["ToastrType"] =
                ToastrType.Error.ToString();

            TempData["ToastrMessage"] =
                ex.Message;

            return RedirectToAction(nameof(Index));
        }
    }


    // POST: Product/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(
        int id,
        ProductViewModel model)
    {
        try
        {
            if (id != model.Id)
            {
                return BadRequest();
            }

            // Existing image paths are not required
            ModelState.Remove(nameof(model.ProductImagePath));
            ModelState.Remove(nameof(model.PicturePath1));
            ModelState.Remove(nameof(model.PicturePath2));
            ModelState.Remove(nameof(model.PicturePath3));
            ModelState.Remove(nameof(model.PicturePath4));

            if (!ModelState.IsValid)
            {
                await LoadDropdowns(model);

                return View(model);
            }

            model.UpdatedBy =
                Convert.ToInt32(
                    HttpContext.Session.GetInt32("UserId"));

            model.UpdatedDate = DateTime.Now;

            using var formData = new MultipartFormDataContent();

            formData.Add(
                new StringContent(model.Id.ToString()),
                nameof(model.Id));

            formData.Add(
                new StringContent(model.Name),
                nameof(model.Name));

            formData.Add(
                new StringContent(model.CategoryId.ToString()),
                nameof(model.CategoryId));

            formData.Add(
                new StringContent(model.SubCategoryId.ToString()),
                nameof(model.SubCategoryId));

            formData.Add(
                new StringContent(model.QuantityPerUnit.ToString()),
                nameof(model.QuantityPerUnit));

            formData.Add(
                new StringContent(model.UnitPrice.ToString()),
                nameof(model.UnitPrice));

            if (model.SizeId.HasValue)
            {
                formData.Add(
                    new StringContent(model.SizeId.Value.ToString()),
                    nameof(model.SizeId));
            }

            if (model.Discount.HasValue)
            {
                formData.Add(
                    new StringContent(model.Discount.Value.ToString()),
                    nameof(model.Discount));
            }

            formData.Add(
                new StringContent(model.UnitInStock.ToString()),
                nameof(model.UnitInStock));

            formData.Add(
                new StringContent(model.UnitInOrder.ToString()),
                nameof(model.UnitInOrder));

            formData.Add(
                new StringContent(model.ProductAvailable.ToString()),
                nameof(model.ProductAvailable));

            if (!string.IsNullOrWhiteSpace(model.ShortDescription))
            {
                formData.Add(
                    new StringContent(model.ShortDescription),
                    nameof(model.ShortDescription));
            }

            if (!string.IsNullOrWhiteSpace(model.LongDescription))
            {
                formData.Add(
                    new StringContent(model.LongDescription),
                    nameof(model.LongDescription));
            }

            // Keep existing image paths
            formData.Add(
                new StringContent(
                    model.ProductImagePath ?? string.Empty),
                nameof(model.ProductImagePath));

            formData.Add(
                new StringContent(
                    model.PicturePath1 ?? string.Empty),
                nameof(model.PicturePath1));

            formData.Add(
                new StringContent(
                    model.PicturePath2 ?? string.Empty),
                nameof(model.PicturePath2));

            formData.Add(
                new StringContent(
                    model.PicturePath3 ?? string.Empty),
                nameof(model.PicturePath3));

            formData.Add(
                new StringContent(
                    model.PicturePath4 ?? string.Empty),
                nameof(model.PicturePath4));

            formData.Add(
                new StringContent(model.IsDeleted.ToString()),
                nameof(model.IsDeleted));

            formData.Add(
                new StringContent(
                    model.UpdatedBy.Value.ToString()),
                nameof(model.UpdatedBy));

            formData.Add(
                new StringContent(
                    model.UpdatedDate.ToDateTimeString()),
                nameof(model.UpdatedDate));

            // Main Product Image
            if (model.ProductImage != null &&
                model.ProductImage.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.ProductImage.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.ProductImage.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.ProductImage),
                    model.ProductImage.FileName);
            }

            // Picture 1
            if (model.Picture1 != null &&
                model.Picture1.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.Picture1.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.Picture1.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.Picture1),
                    model.Picture1.FileName);
            }

            // Picture 2
            if (model.Picture2 != null &&
                model.Picture2.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.Picture2.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.Picture2.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.Picture2),
                    model.Picture2.FileName);
            }

            // Picture 3
            if (model.Picture3 != null &&
                model.Picture3.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.Picture3.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.Picture3.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.Picture3),
                    model.Picture3.FileName);
            }

            // Picture 4
            if (model.Picture4 != null &&
                model.Picture4.Length > 0)
            {
                var imageContent =
                    new StreamContent(
                        model.Picture4.OpenReadStream());

                imageContent.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue(
                        model.Picture4.ContentType);

                formData.Add(
                    imageContent,
                    nameof(model.Picture4),
                    model.Picture4.FileName);
            }

            await _webClient.PutFormAsync<object>(
                $"/api/product/{id}",
                formData);

            TempData["ToastrType"] =
                ToastrType.Success.ToString();

            TempData["ToastrMessage"] =
                "Product updated successfully.";

            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            _logger.LogError(
                "Exception in ProductController Edit POST: {Message}",
                ex.Message);

            TempData["ToastrType"] =
                ToastrType.Error.ToString();

            TempData["ToastrMessage"] =
                ex.Message;

            await LoadDropdowns(model);

            return View(model);
        }
    }

    

    // POST: Product/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            int loginUserId =
                Convert.ToInt32(
                    HttpContext.Session.GetInt32("UserId"));

            await _webClient.DeleteAsync(
                $"/api/product/{id}" +
                $"?loginUserId={loginUserId}" +
                $"&deletedDate={DateTime.Now.ToDateTimeString()}");

            TempData["ToastrType"] =
                ToastrType.Success.ToString();

            TempData["ToastrMessage"] =
                "Product deleted successfully.";
        }
        catch (Exception ex)
        {
            _logger.LogError(
                "Exception in ProductController Delete POST: {Message}",
                ex.Message);

            TempData["ToastrType"] =
                ToastrType.Error.ToString();

            TempData["ToastrMessage"] =
                ex.Message;
        }

        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region AJAX Cascading Dropdowns

    // GET: Product/GetSubCategories?categoryId=1
    [HttpGet]
    public async Task<IActionResult> GetSubCategories(int categoryId)
    {
        try
        {
            var subCategories = await _webClient
                .GetAsync<List<SubCategoryResponseViewModel>>(
                    "/api/subcategory");

            var filteredSubCategories = (subCategories ?? [])
                .Where(x => x.CategoryId == categoryId)
                .ToList();

            return Json(filteredSubCategories);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                "Exception in ProductController GetSubCategories/{categoryId}: {Message}",
                categoryId,
                ex.Message);

            return StatusCode(500);
        }
    }

    #endregion

    #region Private Methods

    private async Task LoadDropdowns(ProductViewModel model)
    {
        var categories = await _webClient
            .GetAsync<List<CategoryViewModel>>(
                "/api/category");

        model.Categories = new SelectList(
            categories ?? new List<CategoryViewModel>(),
            "Id",
            "CategoryName",
            model.CategoryId);


        // Load sub categories for Edit / validation failure
        if (model.CategoryId > 0)
        {
            var subCategories = await _webClient
                .GetAsync<List<SubCategoryViewModel>>(
                    "/api/subcategory");

            var filteredSubCategories = (subCategories ?? [])
                .Where(x => x.CategoryId == model.CategoryId)
                .ToList();

            model.SubCategories = new SelectList(
                filteredSubCategories,
                "Id",
                "SubCategoryName",
                model.SubCategoryId);
        }
        else
        {
            model.SubCategories = new SelectList(
                Enumerable.Empty<SubCategoryViewModel>());
        }


        // Size enum
        var sizes = Enum
            .GetValues<Size>()
            .Select(size => new
            {
                Id = (int)size,
                Name = size.ToString()
            })
            .ToList();

        model.Sizes = new SelectList(
            sizes,
            "Id",
            "Name",
            model.SizeId);
    }

    #endregion


    #region Image Retrieval

    [HttpGet]
    public async Task<IActionResult> Image(string fileName)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(fileName))
            {
                return NotFound();
            }

            var image = await _webClient.GetFileAsync(
                $"/api/product/image/{Uri.EscapeDataString(fileName)}");

            if (image == null || image.Length == 0)
            {
                return NotFound();
            }

            var extension = Path.GetExtension(fileName)
                .ToLowerInvariant();

            var contentType = extension switch
            {
                ".jpg" or ".jpeg" => "image/jpeg",
                ".png" => "image/png",
                ".gif" => "image/gif",
                ".webp" => "image/webp",
                _ => "application/octet-stream"
            };

            return File(image, contentType);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Exception in ProductController Image.");

            return NotFound();
        }
    }

    #endregion


}